# File: codemagic.yaml
workflows:
  EAS Android Build:
    name: EAS Android Build
    environment:
      node: latest
      groups:
        - expo            
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install EAS CLI
        script: |
          npm install -g eas-cli

      - name: Build APK using EAS
        script: |
          eas build --platform android --non-interactive --profile release

    artifacts:
      - "**/*.apk"
