workflows:
  EAS Android Build:
    name: EAS Android Build
    environment:
      node: latest
      vars:
        EXPO_TOKEN: $EXPO_TOKEN   
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Install EAS CLI
        script: |
          npm install -g eas-cli

      - name: Build APK using EAS
        script: |
          # EAS lukee EXPO_TOKEN-ympäristömuuttujan automaattisesti
          eas build --platform android --non-interactive --profile android

    artifacts:
      - "**/*.apk"
