workflows:
  EAS Android Build:
    name: EAS Android Build
    environment:
      groups:
        - expo
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g eas-cli

      - name: Build APK using EAS
        script: |
          eas build --platform android --non-interactive --profile release

    artifacts:
      - "**/*.apk"